### ISSUE TITLE
[META] Project restructure

### ISSUE THREAD

**Issue by dannyhammer** [dannyhammer/toad#75]
**Description:**
Since the merge of #73, the code is in need of better organization. Either use a cargo workspace or just break up the project into individual modules. Core types, board representation, move generation, input handling, engine, and search are all good candidates for modules.

**Relevant Link(s):**

-   https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

**Requirements**:

-   [ ] Determine whether to use a workspace or individual modules
- [ ] Use build scripts, if possible, to precompile things like move tables
- [ ] Split up code into crates/modules
